name: Run Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: 'Playwright and Lint'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-focal
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          options: |
            --no-restore
      - name: Install dependencies
        run: pnpm i
      - name: Run playwright tests
        run: pnpm test:integration
